import type { Vehicle } from './types'

const Elantra: Vehicle[] = [
    {
        maker: 'Hyundai',
        model: 'Elantra',
        trim: 'Blue',
        style: 'Sedan',
        type: 'Hybrid',
        drive: 'Front',
        year: 2023,
        msrp: 24550,
        metadata: {
            mpg: 54,
            fuelCapacity: 11,
            hp: 0,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Elantra',
        trim: 'Limited',
        style: 'Sedan',
        type: 'Hybrid',
        drive: 'Front',
        year: 2023,
        msrp: 29150,
        metadata: {
            mpg: 50,
            fuelCapacity: 11,
            hp: 0,
        },
    },
]

const Kona: Vehicle[] = [
    {
        maker: 'Hyundai',
        model: 'Kona',
        trim: 'SE',
        style: 'SUV',
        drive: 'Front',
        type: 'Gas',
        year: 2023,
        msrp: 22140,
        metadata: {
            mpg: 32,
            fuelCapacity: 13.2,
            hp: 147,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Kona',
        trim: 'SEL',
        style: 'SUV',
        drive: 'Front',
        type: 'Gas',
        year: 2023,
        msrp: 23950,
        metadata: {
            mpg: 32,
            fuelCapacity: 13.2,
            hp: 147,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Kona',
        trim: 'N Line',
        style: 'SUV',
        drive: 'Front',
        type: 'Gas',
        year: 2023,
        msrp: 27850,
        metadata: {
            mpg: 32,
            fuelCapacity: 13.2,
            hp: 195,
        },
    },

    {
        maker: 'Hyundai',
        model: 'Kona',
        trim: 'SE',
        style: 'SUV',
        drive: 'All',
        type: 'Gas',
        year: 2023,
        msrp: 22140,
        metadata: {
            mpg: 30,
            fuelCapacity: 13.2,
            hp: 147,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Kona',
        trim: 'SEL',
        style: 'SUV',
        drive: 'All',
        type: 'Gas',
        year: 2023,
        msrp: 23950,
        metadata: {
            mpg: 30,
            fuelCapacity: 13.2,
            hp: 147,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Kona',
        trim: 'N Line',
        style: 'SUV',
        drive: 'All',
        type: 'Gas',
        year: 2023,
        msrp: 27850,
        metadata: {
            mpg: 29,
            fuelCapacity: 13.2,
            hp: 195,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Kona',
        trim: 'N',
        style: 'SUV',
        drive: 'Front',
        type: 'Gas',
        year: 2023,
        msrp: 34950,
        metadata: {
            mpg: 23,
            fuelCapacity: 13.2,
            hp: 276,
        },
    },
]

const Venue: Vehicle[] = [
    {
        maker: 'Hyundai',
        model: 'Venue',
        trim: 'SE',
        style: 'SUV',
        drive: 'Front',
        type: 'Gas',
        year: 2023,
        msrp: 19650,
        metadata: {
            mpg: 31,
            fuelCapacity: 11.9,
            hp: 121,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Venue',
        trim: 'SEL',
        style: 'SUV',
        drive: 'Front',
        type: 'Gas',
        year: 2023,
        msrp: 21400,
        metadata: {
            mpg: 31,
            fuelCapacity: 11.9,
            hp: 121,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Venue',
        trim: 'Limited',
        style: 'SUV',
        drive: 'Front',
        type: 'Gas',
        year: 2023,
        msrp: 22900,
        metadata: {
            mpg: 31,
            fuelCapacity: 11.9,
            hp: 121,
        },
    },
]

const SantaCruz: Vehicle[] = [
    {
        maker: 'Hyundai',
        model: 'Santa Cruz',
        trim: 'SE',
        style: 'Truck',
        type: 'Gas',
        drive: 'All',
        year: 2023,
        msrp: 0,
        metadata: {
            mpg: 23,
            fuelCapacity: 17.7,
            hp: 191,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Santa Cruz',
        trim: 'SEL',
        style: 'Truck',
        type: 'Gas',
        drive: 'All',
        year: 2023,
        msrp: 0,
        metadata: {
            mpg: 23,
            fuelCapacity: 17.7,
            hp: 191,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Santa Cruz',
        trim: 'Night',
        style: 'Truck',
        type: 'Gas',
        drive: 'All',
        year: 2023,
        msrp: 0,
        metadata: {
            mpg: 23,
            fuelCapacity: 17.7,
            hp: 191,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Santa Cruz',
        trim: 'SEL Premium',
        style: 'Truck',
        type: 'Gas',
        drive: 'All',
        year: 2023,
        msrp: 0,
        metadata: {
            mpg: 23,
            fuelCapacity: 17.7,
            hp: 191,
        },
    },
    {
        maker: 'Hyundai',
        model: 'Santa Cruz',
        trim: 'Limited',
        style: 'Truck',
        type: 'Gas',
        drive: 'All',
        year: 2023,
        msrp: 0,
        metadata: {
            mpg: 23,
            fuelCapacity: 17.7,
            hp: 191,
        },
    },
]

const d = {
    maker: 'Hyundai',
    model: '',
    trim: '',
    style: '',
    type: '',
    year: 0,
    msrp: 0,
    metadata: {
        mpg: 0,
        fuelCapacity: 0,
        hp: 0,
    },
}

export default [...Venue, ...Kona, ...Elantra]
